### PR TITLE
fix(user): `harbor user elevate` to handle empty responses

### LINKED ISSUE #633: `harbor user elevate` executes even in absence of users
# Overview

The `harbor-cli` continue to execute, even there is no user accounts in the registry. 

## Steps to reproduce 

1. Delete all the user accounts in the registry
2. Execute `harbor user elevate`

## Preview

Image

### PR DESCRIPTION
**Pull request by vg006**
# Overview

Fixes #633

The `elevate` sub-command of the `user` command is updated to,
1. Handle empty responses(*payload with no user a/c details*) from registry.
2. Handle the errors and log them properly.

cc: @bupd @NucleoFusion 

## Preview
demo

### CODE REVIEW

**Comment by vg006** [comment]
@qcserestipy As you can see [here](https://github.com/goharbor/harbor-cli/blob/main/cmd/harbor/root/cmd.go#L74-L80), the logger is set with `io.Discard` as a output writer in non-verbose mode, neither used `os.StdOut` nor `os.StdErr` writers. 

So this silences the logrus. I agree that it is logged in the verbose mode, but normally a command should provide a proper closure upon the exit right. So I set it explicitly using the Cobra's writers within the command itself, instead of tweaking the global configuration.

File: cmd/harbor/root/user/delete.go [hunk 1]
```diff
@@ -30,6 +30,7 @@ func UserDeleteCmd() *cobra.Command {
 		Args:  cobra.MinimumNArgs(0),
 		Run: func(cmd *cobra.Command, args []string) {
 			// If there are command line arguments, process them concurrently.
+			log.SetOutput(cmd.OutOrStderr())
```
Comment (bupd) [inline cmd/harbor/root/user/delete.go]: not required. Please remove - we dont use stdErr here.

File: pkg/utils/utils.go [hunk 2]
```diff
@@ -196,23 +196,21 @@ func Capitalize(s string) string {
...
+		log.Fatal(err)
+	}
+	ctx := context.Background()
+	response, err := client.User.ListUsers(ctx, &user.ListUsersParams{})
+	if err != nil {
+		log.Fatal(err)
+	}
+	userId, err := uview.UserList(response.Payload)
+	if err != nil {
+		log.Fatal(err)
```
Comment (bupd) [inline pkg/utils/utils.go:221]: please avoid using Fatal.

Comment (vg006) [reply pkg/utils/utils.go:221]: `log.Fatal` is not introduced in this change, it is presented all across the file.

File: cmd/harbor/root/user/delete.go (hunk 1 above)
Comment (vg006) [reply cmd/harbor/root/user/delete.go]: Removed it.

**Comment by qcserestipy** [comment]
@vg006 @bupd I think changing the styling and color for this command only is not really necessary. Since we return simple text in every other command it could be confusing that it is different here. Just returning the error message as text should be the simplest. I guess `fmt.Errorf` and ` fmt.Printf` should be enough.

**Comment by vg006** [comment]
I thought of improving the UX and I have just used the styles that are already defined in the project. Just added a utility function that returns the given text, wrapped by ANSI sequences.

Fine, then as per your suggestion, let me make this PR minimal. 
But I will propose this type of styled messages in my ongoing work #635, which will have a good impression on the UI and improves usability.

File: cmd/harbor/root/user/delete.go (hunk 1 above)
Comment (bupd) [inline cmd/harbor/root/user/delete.go]: please remove this - not really needed.

Comment (vg006) [reply cmd/harbor/root/user/delete.go]: Done
