### PR TITLE
fix : project logs flags

### LINKED ISSUE #702: bug: `project logs` command flags have no effect
In the `project logs` command, the flags `--page`, `--page-size`, `--query`, `--sort` are defined and and also are accepted as input from the user. 
```
	flags := cmd.Flags()
	flags.Int64VarP(&opts.Page, "page", "", 1, "Page number")
	flags.Int64VarP(&opts.PageSize, "page-size", "", 10, "Size of per page")
	flags.StringVarP(&opts.Q, "query", "q", "", "Query string to query resources")
	flags.StringVarP(&opts.Sort, "sort", "", "", "Sort the resource list in ascending or descending order")
```
The struct `var opts api.ListFlags` in which they are stored is not passed to `api.LosProject()` ,
`resp, err = api.LogsProject(projectName)`
only the projectName is passed

Also in the `project_handler.go`, it only handles logic of accepting only `projectName`
```
func LogsProject(projectName string) (*project.GetLogExtsOK, error) {
	ctx, client, err := utils.ContextWithClient()
	if err != nil {
		return nil, err
	}

	response, err := client.Project.GetLogExts(ctx, &project.GetLogExtsParams{
		ProjectName: projectName,
		Context:     ctx,
	})
	if err != nil {
		return nil, err
	}

	return response, nil
}
```
<hr/>

I am working on this issue.

### PR DESCRIPTION
**Pull request by Sypher845**
Fixes #702 
`--page`, `--page-size`, `--query`, `--sort` flags now work as expected.
In `cmd/harbor/root/project/logs.go` , now the listFlag (opts) is passed.

`resp, err = api.LogsProject(projectName, opts)`

Also the` LogsProject()` now handles the logic of sending the required params

```
func LogsProject(projectName string, opts ...ListFlags) (*project.GetLogExtsOK, error) {
	ctx, client, err := utils.ContextWithClient()
	if err != nil {
		return nil, err
	}

	var listFlags ListFlags
	if len(opts) > 0 {
		listFlags = opts[0]
	}

	response, err := client.Project.GetLogExts(ctx, &project.GetLogExtsParams{
		ProjectName: projectName,
		Page:        &listFlags.Page,
		PageSize:    &listFlags.PageSize,
		Q:           &listFlags.Q,
		Sort:        &listFlags.Sort,
		Context:     ctx,
	})
	if err != nil {
		return nil, err
	}

	return response, nil
}
```

### CODE REVIEW

File: pkg/api/project_handler.go [hunk 1]
```diff
@@ -187,14 +187,23 @@ func SearchProject(query string) (search.SearchOK, error) {
...
 	}
 
+	var listFlags ListFlags
+	if len(opts) > 0 {
+		listFlags = opts[0]
+	}
+
 	response, err := client.Project.GetLogExts(ctx, &project.GetLogExtsParams{
 		ProjectName: projectName,
+		Page:        &listFlags.Page,
```
Comment (qcserestipy) [inline pkg/api/project_handler.go:203]: please validate in the code that pageSize and page cannot be smaller than 0

Comment (Sypher845) [reply pkg/api/project_handler.go:203]: @qcserestipy  for the page-size , i have added it in the PR #631 , will add it for page here

**Comment by Sypher845** [comment]
@qcserestipy done!

File: cmd/harbor/root/project/logs.go [hunk 2]
```diff
@@ -51,7 +51,9 @@ func LogsProjectCommmand() *cobra.Command {
 				}
 				log.Debugf("Project name received from prompt: %s", projectName)
 			}
-
+			if opts.Page < 1 {
+				return fmt.Errorf("page number must be greater than or equal to 1")
+			}
```
[the remark this answers is not in the document]
Comment (Sypher845) [reply cmd/harbor/root/project/logs.go:63]: already added in PR #631, will just need rebasing
