### PR TITLE
tests: Added unit tests for user elevate command

### LINKED ISSUE #591: [CI/Test] Incrementally improve unit test coverage
**Description**
Currently, the code coverage for the project stands at approximately **11%** (according to Codecov). To ensure the stability of the CLI, prevent regressions, and facilitate safer refactoring in the future, we should aim to increase this coverage.

**Proposal**
An incremental approach to improving the test suite is proposed. Rather than attempting a massive overhaul at once, the effort can be broken down into smaller, manageable chunks based on packages or functionality.

**Goals**
* Identify critical paths that are currently untested.
* Add unit tests for utility functions and command logic.

### PR DESCRIPTION
**Pull request by rkcoder101**
## Description
This PR introduces unit tests for the user elevate command (`cmd/harbor/root/user/elevate.go`)

- Fixes #591

## Note

**No** changes have been done to the core logic of the application, only a little refactoring for the purpose of writing some nice and clean test code :)

### CODE REVIEW

**Comment by rkcoder101** [comment]
@bupd please review this whenever u get the time. Thanks!

File: cmd/harbor/root/user/elevate.go [hunk 1]
```diff
@@ -21,46 +21,78 @@ import (
 	"github.com/spf13/cobra"
 )
 
+type UserElevator interface {
```
Comment (qcserestipy) [inline cmd/harbor/root/user/elevate.go]: Introducing a `UserElevator` interface in production code solely for test mockability adds unnecessary complexity. There's only one real implementation (`DefaultUserElevator`), and this pattern isn't used elsewhere in the codebase. Consider restructuring the tests to avoid altering the production code's API surface, or extracting only the testable logic into a separate function.

Comment (rkcoder101) [reply cmd/harbor/root/user/elevate.go]: Hi @qcserestipy I have tried to adapt a different design of test code. I have tried using global functional variables. Kindly review it, and please let me know if there are any changes required in the approach. Thanks!

**Review by qcserestipy — CHANGES_REQUESTED** [review]
@rkcoder101 Thank you for incorporating the changes! LGTM, but please fix the lint issues.

**Comment by rkcoder101** [comment]
> @rkcoder101 Thank you for incorporating the changes! LGTM, but please fix the lint issues.

All the PRs opened lately are facing linting issues. Actually there have been some linting issues on the main recently #711 .  Fellow contributors have raised PRs to solve them, I will rebase as soon as they get merged.
