### PR TITLE
fix(robot_delete): adapt robot api handler for deletion by name; adapt robot delete commands for project and system to allow for deletion by name

### LINKED ISSUE #555: ID column in robot list table not present
Cannot see robot ID in `harbor robot list` 

Image

Deleting a robot requires robot ID.

Image

### PR DESCRIPTION
**Pull request by qcserestipy**
Closes #555

## Overview

This PR introduces changes to improve user experience for project and system robot deletion. It introduces the possibility to delete both kinds of robots by name instead of ID.

## Behavior

https://github.com/user-attachments/assets/7d32f1e0-c2ec-4909-857a-3ad64281ea1b

### CODE REVIEW

File: pkg/api/robot_handler.go [hunk 1]
```diff
@@ -61,6 +62,50 @@ func GetRobot(robotID int64) (*robot.GetRobotByIDOK, error) {
...
+		listResponse, err = ListRobot(ListFlags{})
+		if err != nil {
+			return nil, fmt.Errorf("failed to list robots: %v", utils.ParseHarborErrorMsg(err))
+		}
+	}
+
+	robotID := int64(-1)
+	for _, robotItem := range listResponse.Payload {
+		if robotItem.Name == targetRobotName {
+			robotID = robotItem.ID
```
[the remark this answers is not in the document]
Comment (Vad1mo) [reply pkg/api/robot_handler.go]: @qcserestipy ?

File: cmd/harbor/root/project/robot/delete.go [hunk 2]
```diff
@@ -63,10 +66,20 @@ Examples:
 				err     error
 			)
 			if len(args) == 1 {
-				robotID, err = strconv.ParseInt(args[0], 10, 64)
+				if ProjectName == "" {
+					projectID := prompt.GetProjectIDFromUser()
+					project, err := api.GetProject(strconv.FormatInt(projectID, 10), true)
+					if err != nil {
+						log.Fatalf("failed to get project by name %s: %v", ProjectName, utils.ParseHarborErrorMsg(err))
```
[the remark this answers is not in the document]
Comment (Vad1mo) [reply cmd/harbor/root/project/robot/delete.go]: @qcserestipy ?

File: pkg/api/robot_handler.go [hunk 3]
```diff
@@ -61,7 +62,63 @@ func GetRobot(robotID int64) (*robot.GetRobotByIDOK, error) {
...
+	} else {
+		listResponse, err = ListRobot(ListFlags{
+			Q: "name=" + queryName,
+		})
+		if err != nil {
+			return nil, fmt.Errorf("failed to list robots: %v", utils.ParseHarborErrorMsg(err))
+		}
+	}
+	if len(listResponse.Payload) > 1 {
+		return nil, fmt.Errorf("multiple robots found with name: %v", targetRobotName)
```
Comment (bupd) [inline pkg/api/robot_handler.go:104]: In harbor we usually select the first robot account form the list can you check if this works against same robot account name in both project and system level. 

This might be a edge case.

File: pkg/api/robot_handler.go [hunk 4]
```diff
@@ -61,7 +62,63 @@ func GetRobot(robotID int64) (*robot.GetRobotByIDOK, error) {
...
+	} else if len(listResponse.Payload) == 0 {
+		return nil, fmt.Errorf("no robot found with name: %v, does it exist?", targetRobotName)
+	}
+	response, err := client.Robot.GetRobotByID(ctx, &robot.GetRobotByIDParams{RobotID: listResponse.Payload[0].ID})
```
Comment (bupd) [inline pkg/api/robot_handler.go]: I think we don't need to do the roundtrip again since in the list response already contains the robot details.

**Review by bupd — CHANGES_REQUESTED** [review]
@qcserestipy Thanks for your contribution 

Added my suggestions for possible edge cases and improvements.

File: pkg/api/robot_handler.go (hunk 4 above)
Comment (qcserestipy) [reply pkg/api/robot_handler.go]: Yes, you are absolutely right, I'll remove this.

File: pkg/api/robot_handler.go (hunk 3 above)
Comment (qcserestipy) [reply pkg/api/robot_handler.go:104]: I checked that and it works, that we can separate them. In the project query the project id is required as well as the project name prefix so they are unique in both cases.

**Comment by qcserestipy** [comment]
@bupd Thank you for your review! I incorporated the changes accordingly. In case you have time feel free to have another look.
