### PR TITLE
fix : add url validation to all commands

### LINKED ISSUE #606: Add URL validation to all commands that accept URL input
## Summary
Several CLI commands accept URL inputs but lack proper validation, leading to confusing API errors when invalid URLs are provided.

## Problem
Commands like `instance create`, `registry create/update`, `scanner create/update`, `ldap ping`, and `webhook edit` accept URLs via flags but don't validate them before making API calls. Users see cryptic server errors instead of clear validation messages.

## Solution
Add `utils.ValidateURL()` validation to all commands that accept URL inputs:
- `instance create` - validate `--url` flag
- `registry create` - validate `--url` flag  
- `registry update` - validate `--url` flag
- `scanner create` - validate `--url` flag
- `scanner update` - validate `--url` flag
- `ldap ping` - validate `--ldap-url` flag
- `webhook edit` - validate `--endpoint-url` flag

Also update corresponding view files to use consistent URL validation in interactive forms.

### PR DESCRIPTION
**Pull request by Sypher845**
Fixes #606 
Adds URL validation to commands that accept URL inputs (`instance create`, `registry create/update`, `scanner create/update`, `webhook edit`).

Changes:
- Added `utils.ValidateURL()` checks before API calls
- Updated view files to use consistent URL validation in forms 

### ValidateURL function

What it checks:

* Valid URL format (scheme, host, etc.)
* Host is not empty
* Host is a valid IP or domain name
* Starts/ends with alphanumeric
* Hyphens allowed in middle
* Max 63 chars per label
* TLD at least 2 letters

````
func ValidateURL(rawURL string) error {
	var domainNameRegex = regexp.MustCompile(`^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$`)

	parsedURL, err := url.ParseRequestURI(rawURL)
	if err != nil {
		return fmt.Errorf("invalid URL format: %v", err)
	}

	host := parsedURL.Hostname()
	if host == "" {
		return fmt.Errorf("URL must contain a valid host")
	}

	if net.ParseIP(host) != nil {
		return nil
	}

	if !domainNameRegex.MatchString(host) {
		return fmt.Errorf("invalid host: must be a valid IP address or domain name")
	}

	return nil
}
````

### CODE REVIEW

**Comment by Sypher845** [comment]
@bupd can you please review this

**Comment by Sypher845** [comment]
@bupd i have merged the main branch in this , can you please review again .
Also do i have to make any other changes?

File: pkg/views/scanner/update/view.go [hunk 1]
```diff
@@ -105,7 +105,16 @@ func UpdateScannerView(scanner *models.ScannerRegistration) {
 			huh.NewInput().
 				Title("Scanner Adapter URL").
 				Value(&url).
-				Validate(huh.ValidateNotEmpty()),
+				Validate(func(str string) error {
+					if str == "" {
```
Comment (NucleoFusion) [inline pkg/views/scanner/update/view.go]: Could use `.TrimSpace` like in `pkg/views/registry/update/view.go`

File: pkg/views/webhook/edit/view.go [hunk 2]
```diff
@@ -104,7 +104,15 @@ func WebhookEditView(editView *EditView) {
 
 			huh.NewInput().Title("Endpoint URL").
 				Value(&editView.EndpointURL).
-				Validate(utils.EmptyStringValidator("Endpoint URL")),
+				Validate(func(str string) error {
+					if str == "" {
```
Comment (NucleoFusion) [inline pkg/views/webhook/edit/view.go]: Could use `.TrimSpace` like in `pkg/views/registry/update/view.go`

File: cmd/harbor/root/scanner/update.go [hunk 3]
```diff
@@ -93,7 +94,11 @@ Only the fields passed through flags will be updated; other fields will retain t
 				updateView.AccessCredential = opts.AccessCredential
 			}
 			if flags.Changed("url") {
-				updateView.URL = strfmt.URI(opts.URL)
+				formattedUrl := utils.FormatUrl(opts.URL)
+				if err := utils.ValidateURL(formattedUrl); err != nil {
+					return fmt.Errorf("invalid URL: %v", err)
+				}
```
Comment (NucleoFusion) [inline cmd/harbor/root/scanner/update.go:100]: The function seems to be returning a formatted error, so do we need to do it twice?

Comment (Sypher845) [reply cmd/harbor/root/scanner/update.go:100]: yes , no need for it  
it should  return err directly

**Review by bupd — APPROVED** [review]
please fix the suggestions from copilot - otherwise lgtm
