### PR TITLE
270 add ldflags to dagger

### LINKED ISSUE #270: Version Command is Incorrect
Builds should produce the version command with the correct version.
and provide necessary details.

## Current version Command
```bash
❯ harbor version
Version:      0.1.0
Go version:
Git commit:
Built:
OS/Arch:      linux/amd64
```

## Expected
```bash
❯ harbor version
Version:      v0.0.1
Go version:   go1.23.3
Git commit:   f9a099cd2c763ff8d0c282cd223f626b88caa456
Built:        2024-11-27T20:36:32Z
OS/Arch:      linux/amd64
```

### PR DESCRIPTION
**Pull request by qcserestipy**
Fixes #270 

I added the ldflags to the buildDev and build function to account for the version flags.
Git needs to be installed on the fly in the dagger service to retrieve these values.

### CODE REVIEW

File: dagger/main.go [hunk 1]
```diff
@@ -52,7 +52,19 @@ func (m *HarborCli) BuildDev(
 		WithWorkdir("/src").
 		WithEnvVariable("GOOS", os).
 		WithEnvVariable("GOARCH", arch).
-		WithExec([]string{"go", "build", "-o", "bin/harbor-cli", "cmd/harbor/main.go"})
+		WithExec([]string{"apk", "add", "--no-cache", "git"}).
+		WithExec([]string{
+			"sh",
+			"-c",
+			fmt.Sprintf(`
+				go build -ldflags "-X github.com/goharbor/harbor-cli/cmd/harbor/internal/version.Version=$(git describe --tags --always --dirty 2>/dev/null || echo \"v0.0.1\") \
```
Comment (bupd) [inline dagger/main.go:60]: We can have a static version for BuildDev. Which we can use `dev` as version.

File: dagger/main.go [hunk 2]
```diff
@@ -83,7 +95,19 @@ func (m *HarborCli) build(
 				WithWorkdir("/src").
 				WithEnvVariable("GOOS", goos).
 				WithEnvVariable("GOARCH", goarch).
-				WithExec([]string{"go", "build", "-o", bin_path + "harbor", "/src/cmd/harbor/main.go"}).
+				WithExec([]string{"apk", "add", "--no-cache", "git"}).
+				WithExec([]string{
+					"sh",
+					"-c",
+					fmt.Sprintf(`
+						go build -ldflags "-X github.com/goharbor/harbor-cli/cmd/harbor/internal/version.Version=$(git describe --tags --always --dirty 2>/dev/null || echo \"v0.0.1\") \
```
Comment (bupd) [inline dagger/main.go:103]: There should be no fallback on version for production builds.

File: dagger/harbor-dev
Comment (bupd) [inline dagger/harbor-dev:1]: Remove bin files.

File: dagger/main.go [hunk 3]
```diff
@@ -83,7 +95,19 @@ func (m *HarborCli) build(
...
+								  -X github.com/goharbor/harbor-cli/cmd/harbor/internal/version.GoVersion=$(go version | awk '{print $3}') \
+								  -X github.com/goharbor/harbor-cli/cmd/harbor/internal/version.GitCommit=$(git rev-parse --short HEAD) \
+								  -X github.com/goharbor/harbor-cli/cmd/harbor/internal/version.BuildTime=$(date -u +"%%Y-%%m-%%dT%%H:%%M:%%SZ") \
+								  -X github.com/goharbor/harbor-cli/cmd/harbor/internal/version.System=$(go env GOOS)/$(go env GOARCH)" \
```
Comment (bupd) [inline dagger/main.go:107]: Os and arch will be auto-generated by version command.

**Review by bupd — CHANGES_REQUESTED** [review]

**Review by bupd — CHANGES_REQUESTED** [review]
Remove the binary file `harbor-dev`.

**Review by bupd — APPROVED** [review]
LGTM!

**Comment by bupd** [comment]
@Vad1mo, if you're okay with the changes, we can proceed with merging this.

**Review by Vad1mo — APPROVED** [review]
